language: rust

os:
- linux

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true

script:
  - rustup component add rustfmt
  - cargo fmt -- --check
  - cargo test --all --all-features

env:
  global:
    - CONSUL_VERSION=1.4.0
    - CONSUL_DC=dev1
    - CONSUL_DIR=$HOME/consul_$CONSUL_VERSION

before_script:
  - 'if [[ ! -f $CONSUL_DIR/consul ]]; then (mkdir -p $CONSUL_DIR && cd $CONSUL_DIR && wget https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip && unzip consul_${CONSUL_VERSION}_linux_amd64.zip); fi'
    - export $PATH="${CONSUL_DIR}:$PATH"
  - consul --version
  - consul agent -dev &

cache:
  directories:
    - $CONSUL_DIR
